### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by matthewp** [bitovi/dog-things-react#1]
This is an example app for an ecommerce style application. The elements include:

* A header section containing
  * The site name
  * A cart (with its count)
* A sidebar for filtering by content type
* A list of items within the selected category

The design of the app looks like this currently:

<img width="1281" alt="dog things react - ugly" src="https://user-images.githubusercontent.com/361671/51265525-fc41e600-1986-11e9-8e16-a0c3f3fab5ea.png">

A designer who could come up with a better design is wanted. It's pretty much in their hands to do what they want, the only important parts are:

* The cart needs to at the top of the page some where. This is so we can show its count updating later than other parts of the page.
* Each list item should have a height so that we can see at least 3 items within the viewport of a normal browser size but less than all of the items at once.

---

Getting setup is easy here just:

1. Clone this repository.
1. Run `npm install`.
1. Run `npm start`.
1. A browser window will open for you. 
1. Edit any of the .css files as you wish.
1. The browser should automatically refresh for you.

That is all.

**Comment by matthewp** [comment]
@adrifolio agreed to help. 👏Adri!

**Comment by adrifolio** [comment]
I'm happy to! @matthewp a clarification on this point:

`Each list item should have a height so that we can see at least 3 items within the viewport of a normal browser size but less than all of the items at once.`

This part:
`Each list item should have a height so that we can see at least 3 items within the viewport of a normal browser size`

is clear to me, but I'm not sure what you mean by

`but less than all of the items at once`

**Comment by matthewp** [comment]
@adrifolio The list uses fixture data. There are 9 items in the list. I just want to make sure that it's still a scrollable list; you can't see all 9 items without scrolling. But the screenshot of how it looks now means you can only see 2 and a half items without scrolling. That's not enough to get the effect I am going for (where items are streamed in one-by-one). Does that explain it better? If not we can hop on a call together.

**Comment by matthewp** [comment]
@adrifolio There's one other minor thing that would be nice. This is an example app that uses React. There will be another example app that uses [Vue](https://vuejs.org/) and a third that uses [Angular](https://angular.io/).

They will all use the same styles, but it would be nice if it were themeable some how. Just some small visual flare, like a different color somewhere that matched React's color scheme vs Vues, etc.

**Comment by adrifolio** [comment]
> @adrifolio The list uses fixture data. There are 9 items in the list. I just want to make sure that it's still a scrollable list; you can't see all 9 items without scrolling. But the screenshot of how it looks now means you can only see 2 and a half items without scrolling. That's not enough to get the effect I am going for (where items are streamed in one-by-one). Does that explain it better? If not we can hop on a call together.

So keep the list scrollable with at least 3 items fitting on the viewport without scrolling. Does that sound right?

**Comment by matthewp** [comment]
Yep, that sounds exactly right! Actually you can ignore the upper limit. Fit as many as you think is appropriate and I can always add more data to make the list scrollable.

**Comment by adrifolio** [comment]
@matthewp this is what I came up with:

<img width="1389" alt="screen shot 2019-01-18 at 8 09 29 am" src="https://user-images.githubusercontent.com/950214/51391716-704fcb80-1af8-11e9-82b1-b24184b07a2d.png">

And this shows the different themes:
<img width="1183" alt="screen shot 2019-01-17 at 8 39 52 pm" src="https://user-images.githubusercontent.com/950214/51391511-dee05980-1af7-11e9-9dd7-8320356bac9c.png">

The vertical card might not work as well since some products have very long descriptions, so once I work on the implementation I might go with a horizontal version.

Can you give me permission to push on this repo?

**Comment by matthewp** [comment]
omg this looks amazing. I'm not sure how the horizontal layout will work either, but I love the way it looks. I'll post a gif once I try it out in the app.

We could make it vertical by truncating the description with `text-overflow: ellipsis;` and have a `more` link that expands.

**Comment by matthewp** [comment]
You should have permission now.

**Comment by adrifolio** [comment]
Thank you!
